apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - opencost
  - gateway-api
  - loki
  # - tempo-distributed
  - tempo
  - istio
  - istio-ingress
  # - kiali
  - linkerd
  - linkerd-jaeger
  - linkerd-smi
  - linkerd-viz
  - flagger
  - redis
  - oauth2-proxy
  - postgres
  # - mysql
  - mongodb
  # - elasticsearch
  # - kafka
  - rabbitmq
  - chaos-mesh
  - botkube
  - flux
  - vsc
  - postfix
  - azure-workload-identity
  - dapr
  - keda
  - keda-http
  # - pulsar
  - keycloak-operator
  - qdrant